version: "3"
services:
  getnet-api:
    container_name: 'getnet-api'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '8080:8080'
    env_file: .env
